### ISSUE TITLE
Not able to add Contact

### ISSUE THREAD

**Issue by yogesh-patel** [rt2zz/react-native-addressbook#5]
I tried to add contact (as mentioned in example) by using AddressBook.addContact(newPerson, (err) => { console.log("error::::::"+err)}); I am getting error each time.  I checked permission , its 'authorized' and 'err' coming in callback is null.

**Comment by rt2zz** [comment]
woops, should be fixed now in v1.2.0

**Comment by yogesh-patel** [comment]
Just tried with v1.2.0, still same error I am getting.

**Comment by rt2zz** [comment]
check out the demo project: https://github.com/rt2zz/react-native-addressbook/blob/master/examples/AddressbookDemo/index.ios.js

there was an error before, but I fixed it, and it is definitely working for me in 1.2.0

**Comment by yogesh-patel** [comment]
Yes!!! its working.. Thank You :)
