### ISSUE TITLE
Slow access

### ISSUE THREAD

**Issue by AdamBrodzinski** [rt2zz/react-native-addressbook#7]
I've had an issue with a beta tester opening up the contacts and it took 8-10 seconds for the contacts to load (ios8, iPhone 5, and 700 contacts). Have you had any issues like this? It takes around 1-1.5 seconds on my 6. I guess I can cache them on startup after it's confirmed to mitigate this.

**Comment by rt2zz** [comment]
hmm. there is probably a lot of performance gains to be had by translating to contact object into a dictionary more efficiently. 

It would certainly be worth experiment ing and profiling.

**Comment by rt2zz** [comment]
@AdamBrodzinski I believe accessing that many items out of the iOS database is probably always going to be somewhat slow, but here is what we can potentially do in the future:
1. Stream / Batch Process results
2. Implement `get` with options, that will allow querying for smaller result sets, and potetntially paging over them
3. Load the contact data in the background as soon as possible and cache it for later use.

Option 3 Is of course the easiest to implement both module side and application side, although it may not work for all use cases (e.g. if the first screen of your app requires displaying contacts).

Future development will be going on at [react-native-contacts](https://github.com/rt2zz/react-native-contacts), including moving from AddressBook to Contacts API (iOS 9+) - any future performance improvements would happen over there.
