### ISSUE TITLE
Request permissions doesn't actually request

### ISSUE THREAD

**Issue by masonoise** [rt2zz/react-native-addressbook#8]
If I understand it correctly, calling `requestPermission()` should display the dialog asking the user for permissions, but it doesn't seem to do that. I have a code block:

```
AddressBook.requestPermission( (err, permission) => {
    console.log('Returning, permission=' + permission);
    return(permission === 'authorized');
}
```

When this is called I can see the log, and it is always printing 'denied'. I expected that `checkPermission()` would check and return the current permission, while `requestPermission()` would display the request to the user again to grant permissions. What's the expected behavior?

Thanks very much.

**Comment by rt2zz** [comment]
`requestPermission` calls `ABAddressBookRequestAccessWithCompletion` in iOS. Per the iOS docs, If the user has already granted or denied permission, the method does nothing: `The user is only asked for permission the first time you request access. Later calls use the permission granted by the user.`

As far as I know apple does not provide a way to "re-prompt" for a previously denied permission.

**Comment by masonoise** [comment]
Yeah, I've been researching and was starting to get that impression. I had thought that even if permission was denied initially, calling `requestPermission()` would re-prompt, but apparently not as I dug down into the iOS code. Thanks for your reply and confirmation.

**Comment by rt2zz** [comment]
Moving development to https://github.com/rt2zz/react-native-contacts.

I added a note over there that requestPermission does not re-request if permission has already been granted or denied.

If you find you need different permissions methods let me know and we can consider changing the API
