### ISSUE TITLE
[question] Group support

### ISSUE THREAD

**Issue by chrise86** [rt2zz/react-native-addressbook#9]
Great library, just wondering if you have any idea of an ETA for group support?

**Comment by rt2zz** [comment]
No eta, but PRs welcome :)

First order of business is android support.

**Comment by rt2zz** [comment]
hey @chrise86, I just release the (work in progress) successor to this module: [react-native-contacts](https://github.com/rt2zz/react-native-contacts)

If you need group support and have the capacity to contribute code or money, I encourage you to file an issue over there.

Also if you can provide a proposal for a hypthetical contact groups API, it would help expedite any potential implementation.
